CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()), 
    [IdentityId] UNIQUEIDENTIFIER NOT NULL, 
    [GivenName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [CreatedAt] DATETIME NOT NULL DEFAULT (GETUTCDATE()), 
    [UdatedAt] DATETIME NOT NULL DEFAULT (GETUTCDATE()), 
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_Users_Users_IdentityId] FOREIGN KEY ([IdentityId]) REFERENCES [identity].[Users]([Id]) 
)

GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_User_IdentityId] ON [dbo].[Users] ([IdentityId])
